### ISSUE TITLE
Make Final Code Edits/Updates for Sprint #1

### ISSUE THREAD

**Issue by savannahmccoy** [DevOps-Promo/promotions#28]
**As a** developer
**I need** review to code and sprint goals
**So that** I can make sure everything for the sprint is complete

**Assumptions:** 
* The sprint is almost complete

**Acceptance Criteria:**
```
Given everything is checked off
When I compare the aspects of the project to the checklist
Then the sprint is complete and the developers can move on to the next sprint
```

**Comment by jc5808** [comment]
@savannahmccoy should we reassign this to Sprint 2 since this is the first part of the HW for this sprint. Thoughts?
