### ISSUE TITLE
Create Cloud Foundry Metadata Files

### ISSUE THREAD

**Issue by savannahmccoy** [DevOps-Promo/promotions#32]
**As a** developer
**I need** to create the necessary Cloud Foundry metadata files for deployment
**So that**  IBM Cloud will know how to deploy the application

**Assumptions:** 
* The necessary files are manifest.yml, Procfile, runtime.txt

**Acceptance Criteria:**
```
Given the Cloud Foundry metadata files have been created
When we attempt to deploy the project
Then it will be successfully deployed
```

**Comment by savannahmccoy** [comment]
most of the files are there already

**Comment by jc5808** [comment]
Oops. Didn't meant to change the estimate. Changed back to original.
