### ISSUE TITLE
Connect ElephantSQL Database to Python App within IBMCloud

### ISSUE THREAD

**Issue by crb618** [DevOps-Promo/promotions#46]
**As a** Developer
**I need** the SQL Database to be available within IBM cloud
**So that** the Python app is able to store data

**Assumptions:** 
* Elephant SQL database is set up 

**Acceptance Criteria:**
```
Given ... a team member opens ibm cloud
When ... the dashboard is opened
Then ... we can see the Python app and elephantSQL connection in the dashboard
```

**Comment by jc5808** [comment]
Moving this to done as the ElephantSQL database was already connected to the Promotions App via the manifest.yml file. 

@savannahmccoy also made a few updates to the models and test file to make sure the database was working properly.
