### ISSUE TITLE
Test & Debug Cloud API Functions

### ISSUE THREAD

**Issue by Roopgill** [DevOps-Promo/promotions#47]
**As a** Developer 
**I need** to debug and test the cloud API functions
**So that** the API is functioning and accessible

**Assumptions:** 
* Attempts to interact with the API on the cloud produce errors

**Acceptance Criteria:**
```
Given that the functions are working
When we test them from the browser
Then we will be able to successfully perform API functions
```

**Comment by jc5808** [comment]
This is first step in Sprint 3. Need to redeploy to IBM to ensure API is working. Reassigning to Sprint 3.
