### ISSUE TITLE
Create a promotion in BDD

### ISSUE THREAD

**Issue by Roopgill** [DevOps-Promo/promotions#57]
**As a** Marketing manager
**I need** to Create a promotion
**So that** our customers are able to access a new promotion

**Assumptions:** 
* ElephantSQL database is connected to python application

**Acceptance Criteria:**
```
Given that there are 3 promotions in the database 
When I add 1 more new promotion
Then there are 4 promotions in the database
```

**Comment by jc5808** [comment]
Just making a note that I fixed the create promotion BDD in the feature file when I made some other changes. Pull request was already completed so moving this to done.
